module.exports = {
  job: [
    {
      JOB_ID: 1,
      ONET_SOC: '15-1121.00',
      date_posted: '2017-02-19',
      job_title: 'Systems Analyst',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 27,
      age_high: 35,
      exp_low: 1,
      exp_high: 3,
      no_position: 1,
      ONET_Title: 'Computer Systems Analysts',
      Region: 'North',
      Facullty: 'Engineering',
    },
    {
      JOB_ID: 2,
      ONET_SOC: '17-2072.00',
      date_posted: '2017-02-19',
      job_title: 'SCM Engineer Staff',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 25,
      age_high: 30,
      exp_low: 1,
      exp_high: 99,
      no_position: 1,
      ONET_Title: 'Electronics Engineers, Except Computer',
      Region: 'South',
      Facullty: 'Psychology',
    },
    {
      JOB_ID: 3,
      ONET_SOC: '15-1121.00',
      date_posted: '2017-02-19',
      job_title: '.NET Developer (C#)',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 0,
      age_high: 99,
      exp_low: 0,
      exp_high: 99,
      no_position: 1,
      ONET_Title: 'Computer Systems Analysts',
      Region: 'East',
      Facullty: 'Arts',
      'Reading Comprehension': 1,
      'Active Listening': 1,
      Writing: 1,
      Speaking: 0,
      Mathematics: 0,
      Science: 1,
      'Critical Thinking': 1,
      'Active Learning': 0,
      'Learning Strategies': 0,
      Monitoring: 1,
      'Social Perceptiveness': 1,
      Coordination: 0,
      Persuasion: 0,
      Negotiation: 1,
      Instructing: 0,
      'Service Orientation': 1,
      'Complex Problem Solving': 0,
      'Operations Analysis': 0,
      'Technology Design': 1,
      'Equipment Selection': 1,
      Installation: 1,
      Programming: 0,
      'Operation Monitoring': 0,
      'Operation and Control': 0,
      'Equipment Maintenance': 0,
      Troubleshooting: 1,
      Repairing: 0,
      'Quality Control Analysis': 0,
      'Judgment and Decision Making': 1,
      'Systems Analysis': 1,
      'Systems Evaluation': 1,
      'Time Management': 1,
      'Management of Financial Resources': 0,
      'Management of Material Resources': 1,
      'Management of Personnel Resources': 0,
      'Administration and Management': 0,
      Clerical: 1,
      'Economics and Accounting': 0,
      'Sales and Marketing': 0,
      'Customer and Personal Service': 0,
      'Personnel and Human Resources': 1,
      'Production and Processing': 1,
      'Food Production': 1,
      'Computers and Electronics': 0,
      'Engineering and Technology': 1,
      Design: 1,
      'Building and Construction': 1,
      Mechanical: 1,
      Physics: 1,
      Chemistry: 0,
      Biology: 1,
      Psychology: 1,
      'Sociology and Anthropology': 1,
      Geography: 1,
      'Medicine and Dentistry': 1,
      'Therapy and Counseling': 1,
      'Education and Training': 0,
      'English Language': 0,
      'Foreign Language': 1,
      'Fine Arts': 1,
      'History and Archeology': 0,
      'Philosophy and Theology': 0,
      'Public Safety and Security': 0,
      'Law and Government': 0,
      Telecommunications: 0,
      'Communications and Media': 0,
      Transportation: 0,
      'Document management software': 1,
      'Content workflow software': 1,
      'Customer relationship management CRM software': 0,
      'Enterprise resource planning ERP software': 1,
      'Enterprise application integration software': 1,
      'Accounting software': 1,
      'Data base user interface and query software': 1,
      'Spreadsheet software': 0,
      'Electronic mail software': 0,
      'Presentation software': 0,
      'Project management software': 0,
      'Desktop publishing software': 0,
      'Word processing software': 0,
      'Web platform development software': 0,
      'Data base management system software': 0,
      'Graphics or photo imaging software': 1,
      'Video creation and editing software': 0,
      'Computer aided design CAD software': 1,
      'Access software': 1,
      'Computer aided manufacturing CAM software': 1,
      'Transaction server software': 0,
      'Web page creation and editing software': 0,
      'Sales and marketing software': 1,
      'Data mining software': 0,
      'Human resources software': 1,
      'Business intelligence and data analysis software': 0,
      'Communications server software': 1,
      'Enterprise system management software': 1,
      'Analytical or scientific software': 1,
      'Operating system software': 1,
      'Information retrieval or search software': 1,
      'Transaction security and virus protection software': 0,
      'Development environment software': 1,
      'Network monitoring software': 1,
      'Financial analysis software': 1,
      'Object oriented data base management software': 0,
      'Configuration management software': 0,
      'Object or component oriented development software': 1,
      'Data base reporting software': 1,
      'Backup or archival software': 1,
      'Portal server software': 1,
      'Metadata management software': 1,
      'Application server software': 1,
      'Requirements analysis and system architecture software': 0,
      'Network security and virtual private network VPN equipment software': 1,
      'Medical software': 1,
      'Program testing software': 0,
      'Map creation software': 1,
      'File versioning software': 1,
      'Network security or virtual private network VPN management software': 1,
      'Tax preparation software': 1,
      'Computer based training software': 1,
      'Digital pen': 1,
    },
    {
      JOB_ID: 4,
      ONET_SOC: '15-1121.00',
      date_posted: '2017-02-22',
      job_title: 'Computer S',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 23,
      age_high: 36,
      exp_low: 1,
      exp_high: 99,
      no_position: 3,
      ONET_Title: 'Computer Systems Analysts',
      Region: 'West',
      Facullty: 'Science',
      'Reading Comprehension': 0,
      'Active Listening': 0,
      Writing: 3,
      Speaking: 3,
      Mathematics: 3,
      Science: 3,
      'Critical Thinking': 3,
      'Active Learning': 3,
      'Learning Strategies': 0,
      Monitoring: 0,
      'Social Perceptiveness': 0,
      Coordination: 3,
      Persuasion: 3,
      Negotiation: 0,
      Instructing: 0,
      'Service Orientation': 3,
      'Complex Problem Solving': 3,
      'Operations Analysis': 0,
      'Technology Design': 0,
      'Equipment Selection': 0,
      Installation: 0,
      Programming: 3,
      'Operation Monitoring': 3,
      'Operation and Control': 3,
      'Equipment Maintenance': 3,
      Troubleshooting: 0,
      Repairing: 0,
      'Quality Control Analysis': 0,
      'Judgment and Decision Making': 0,
      'Systems Analysis': 3,
      'Systems Evaluation': 3,
      'Time Management': 3,
      'Management of Financial Resources': 0,
      'Management of Material Resources': 3,
      'Management of Personnel Resources': 0,
      'Administration and Management': 0,
      Clerical: 3,
      'Economics and Accounting': 3,
      'Sales and Marketing': 3,
      'Customer and Personal Service': 0,
      'Personnel and Human Resources': 0,
      'Production and Processing': 3,
      'Food Production': 0,
      'Computers and Electronics': 0,
      'Engineering and Technology': 3,
      Design: 3,
      'Building and Construction': 3,
      Mechanical: 3,
      Physics: 0,
      Chemistry: 3,
      Biology: 0,
      Psychology: 0,
      'Sociology and Anthropology': 0,
      Geography: 3,
      'Medicine and Dentistry': 0,
      'Therapy and Counseling': 0,
      'Education and Training': 0,
      'English Language': 0,
      'Foreign Language': 3,
      'Fine Arts': 3,
      'History and Archeology': 0,
      'Philosophy and Theology': 3,
      'Public Safety and Security': 0,
      'Law and Government': 0,
      Telecommunications: 3,
      'Communications and Media': 0,
      Transportation: 0,
      'Document management software': 0,
      'Content workflow software': 3,
      'Customer relationship management CRM software': 0,
      'Enterprise resource planning ERP software': 0,
      'Enterprise application integration software': 0,
      'Accounting software': 0,
      'Data base user interface and query software': 0,
      'Spreadsheet software': 0,
      'Electronic mail software': 0,
      'Presentation software': 0,
      'Project management software': 0,
      'Desktop publishing software': 0,
      'Word processing software': 3,
      'Web platform development software': 3,
      'Data base management system software': 3,
      'Graphics or photo imaging software': 3,
      'Video creation and editing software': 3,
      'Computer aided design CAD software': 3,
      'Access software': 0,
      'Computer aided manufacturing CAM software': 0,
      'Transaction server software': 3,
      'Web page creation and editing software': 0,
      'Sales and marketing software': 0,
      'Data mining software': 0,
      'Human resources software': 3,
      'Business intelligence and data analysis software': 0,
      'Communications server software': 3,
      'Enterprise system management software': 0,
      'Analytical or scientific software': 3,
      'Operating system software': 0,
      'Information retrieval or search software': 3,
      'Transaction security and virus protection software': 3,
      'Development environment software': 3,
      'Network monitoring software': 3,
      'Financial analysis software': 0,
      'Object oriented data base management software': 3,
      'Configuration management software': 0,
      'Object or component oriented development software': 0,
      'Data base reporting software': 3,
      'Backup or archival software': 0,
      'Portal server software': 0,
      'Metadata management software': 0,
      'Application server software': 0,
      'Requirements analysis and system architecture software': 0,
      'Network security and virtual private network VPN equipment software': 3,
      'Medical software': 0,
      'Program testing software': 0,
      'Map creation software': 3,
      'File versioning software': 3,
      'Network security or virtual private network VPN management software': 0,
      'Tax preparation software': 3,
      'Computer based training software': 0,
      'Digital pen': 3,
    },
    {
      JOB_ID: 5,
      ONET_SOC: '15-1121.00',
      date_posted: '2017-02-22',
      job_title: 'Computer S',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 26,
      age_high: 41,
      exp_low: 2,
      exp_high: 99,
      no_position: 2,
      ONET_Title: 'Computer Systems Analysts',
      Region: 'Northeast',
      Facullty: 'Engineering',
      'Reading Comprehension': 0,
      'Active Listening': 0,
      Writing: 2,
      Speaking: 0,
      Mathematics: 0,
      Science: 2,
      'Critical Thinking': 0,
      'Active Learning': 0,
      'Learning Strategies': 2,
      Monitoring: 2,
      'Social Perceptiveness': 0,
      Coordination: 0,
      Persuasion: 0,
      Negotiation: 2,
      Instructing: 0,
      'Service Orientation': 2,
      'Complex Problem Solving': 0,
      'Operations Analysis': 0,
      'Technology Design': 2,
      'Equipment Selection': 0,
      Installation: 0,
      Programming: 2,
      'Operation Monitoring': 2,
      'Operation and Control': 2,
      'Equipment Maintenance': 2,
      Troubleshooting: 0,
      Repairing: 0,
      'Quality Control Analysis': 2,
      'Judgment and Decision Making': 0,
      'Systems Analysis': 0,
      'Systems Evaluation': 0,
      'Time Management': 2,
      'Management of Financial Resources': 2,
      'Management of Material Resources': 0,
      'Management of Personnel Resources': 0,
      'Administration and Management': 0,
      Clerical: 0,
      'Economics and Accounting': 0,
      'Sales and Marketing': 2,
      'Customer and Personal Service': 0,
      'Personnel and Human Resources': 2,
      'Production and Processing': 2,
      'Food Production': 0,
      'Computers and Electronics': 0,
      'Engineering and Technology': 2,
      Design: 2,
      'Building and Construction': 0,
      Mechanical: 0,
      Physics: 2,
      Chemistry: 2,
      Biology: 0,
      Psychology: 2,
      'Sociology and Anthropology': 2,
      Geography: 0,
      'Medicine and Dentistry': 0,
      'Therapy and Counseling': 2,
      'Education and Training': 0,
      'English Language': 2,
      'Foreign Language': 2,
      'Fine Arts': 2,
      'History and Archeology': 0,
      'Philosophy and Theology': 0,
      'Public Safety and Security': 2,
      'Law and Government': 0,
      Telecommunications: 2,
      'Communications and Media': 0,
      Transportation: 0,
      'Document management software': 2,
      'Content workflow software': 2,
      'Customer relationship management CRM software': 2,
      'Enterprise resource planning ERP software': 2,
      'Enterprise application integration software': 0,
      'Accounting software': 0,
      'Data base user interface and query software': 2,
      'Spreadsheet software': 0,
      'Electronic mail software': 2,
      'Presentation software': 0,
      'Project management software': 0,
      'Desktop publishing software': 2,
      'Word processing software': 0,
      'Web platform development software': 2,
      'Data base management system software': 0,
      'Graphics or photo imaging software': 0,
      'Video creation and editing software': 0,
      'Computer aided design CAD software': 0,
      'Access software': 0,
      'Computer aided manufacturing CAM software': 2,
      'Transaction server software': 0,
      'Web page creation and editing software': 0,
      'Sales and marketing software': 2,
      'Data mining software': 2,
      'Human resources software': 2,
      'Business intelligence and data analysis software': 2,
      'Communications server software': 2,
      'Enterprise system management software': 0,
      'Analytical or scientific software': 2,
      'Operating system software': 0,
      'Information retrieval or search software': 0,
      'Transaction security and virus protection software': 0,
      'Development environment software': 0,
      'Network monitoring software': 0,
      'Financial analysis software': 0,
      'Object oriented data base management software': 2,
      'Configuration management software': 2,
      'Object or component oriented development software': 0,
      'Data base reporting software': 0,
      'Backup or archival software': 2,
      'Portal server software': 2,
      'Metadata management software': 2,
      'Application server software': 0,
      'Requirements analysis and system architecture software': 2,
      'Network security and virtual private network VPN equipment software': 2,
      'Medical software': 0,
      'Program testing software': 0,
      'Map creation software': 2,
      'File versioning software': 2,
      'Network security or virtual private network VPN management software': 2,
      'Tax preparation software': 0,
      'Computer based training software': 2,
      'Digital pen': 2,
    },
    {
      JOB_ID: 6,
      ONET_SOC: '15-1121.00',
      date_posted: '2017-02-22',
      job_title: 'Computer S',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 23,
      age_high: 27,
      exp_low: 1,
      exp_high: 99,
      no_position: 1,
      ONET_Title: 'Computer Systems Analysts',
      Region: 'Central',
      Facullty: 'Engineering',
      'Reading Comprehension': 0,
      'Active Listening': 0,
      Writing: 0,
      Speaking: 1,
      Mathematics: 0,
      Science: 1,
      'Critical Thinking': 1,
      'Active Learning': 0,
      'Learning Strategies': 1,
      Monitoring: 0,
      'Social Perceptiveness': 0,
      Coordination: 1,
      Persuasion: 0,
      Negotiation: 1,
      Instructing: 0,
      'Service Orientation': 1,
      'Complex Problem Solving': 1,
      'Operations Analysis': 0,
      'Technology Design': 0,
      'Equipment Selection': 1,
      Installation: 0,
      Programming: 0,
      'Operation Monitoring': 0,
      'Operation and Control': 0,
      'Equipment Maintenance': 0,
      Troubleshooting: 1,
      Repairing: 1,
      'Quality Control Analysis': 0,
      'Judgment and Decision Making': 0,
      'Systems Analysis': 1,
      'Systems Evaluation': 1,
      'Time Management': 1,
      'Management of Financial Resources': 0,
      'Management of Material Resources': 1,
      'Management of Personnel Resources': 1,
      'Administration and Management': 0,
      Clerical: 1,
      'Economics and Accounting': 0,
      'Sales and Marketing': 1,
      'Customer and Personal Service': 1,
      'Personnel and Human Resources': 1,
      'Production and Processing': 1,
      'Food Production': 0,
      'Computers and Electronics': 0,
      'Engineering and Technology': 1,
      Design: 1,
      'Building and Construction': 0,
      Mechanical: 0,
      Physics: 0,
      Chemistry: 1,
      Biology: 1,
      Psychology: 1,
      'Sociology and Anthropology': 1,
      Geography: 0,
      'Medicine and Dentistry': 0,
      'Therapy and Counseling': 1,
      'Education and Training': 1,
      'English Language': 1,
      'Foreign Language': 0,
      'Fine Arts': 0,
      'History and Archeology': 1,
      'Philosophy and Theology': 1,
      'Public Safety and Security': 1,
      'Law and Government': 0,
      Telecommunications: 0,
      'Communications and Media': 0,
      Transportation: 1,
      'Document management software': 1,
      'Content workflow software': 0,
      'Customer relationship management CRM software': 0,
      'Enterprise resource planning ERP software': 1,
      'Enterprise application integration software': 1,
      'Accounting software': 1,
      'Data base user interface and query software': 1,
      'Spreadsheet software': 0,
      'Electronic mail software': 1,
      'Presentation software': 0,
      'Project management software': 1,
      'Desktop publishing software': 0,
      'Word processing software': 1,
      'Web platform development software': 1,
      'Data base management system software': 0,
      'Graphics or photo imaging software': 0,
      'Video creation and editing software': 0,
      'Computer aided design CAD software': 0,
      'Access software': 1,
      'Computer aided manufacturing CAM software': 0,
      'Transaction server software': 0,
      'Web page creation and editing software': 1,
      'Sales and marketing software': 0,
      'Data mining software': 1,
      'Human resources software': 0,
      'Business intelligence and data analysis software': 1,
      'Communications server software': 0,
      'Enterprise system management software': 1,
      'Analytical or scientific software': 1,
      'Operating system software': 1,
      'Information retrieval or search software': 0,
      'Transaction security and virus protection software': 0,
      'Development environment software': 0,
      'Network monitoring software': 1,
      'Financial analysis software': 1,
      'Object oriented data base management software': 0,
      'Configuration management software': 1,
      'Object or component oriented development software': 1,
      'Data base reporting software': 1,
      'Backup or archival software': 0,
      'Portal server software': 0,
      'Metadata management software': 0,
      'Application server software': 1,
      'Requirements analysis and system architecture software': 0,
      'Network security and virtual private network VPN equipment software': 0,
      'Medical software': 1,
      'Program testing software': 0,
      'Map creation software': 0,
      'File versioning software': 0,
      'Network security or virtual private network VPN management software': 0,
      'Tax preparation software': 0,
      'Computer based training software': 0,
      'Digital pen': 1,
    },
    {
      JOB_ID: 7,
      ONET_SOC: '15-1121.00',
      date_posted: '2017-02-22',
      job_title: 'Computer S',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 27,
      age_high: 41,
      exp_low: 0,
      exp_high: 99,
      no_position: 1,
      ONET_Title: 'Computer Systems Analysts',
      Region: 'Central',
      Facullty: 'Engineering',
      'Reading Comprehension': 0,
      'Active Listening': 1,
      Writing: 0,
      Speaking: 0,
      Mathematics: 1,
      Science: 0,
      'Critical Thinking': 1,
      'Active Learning': 1,
      'Learning Strategies': 1,
      Monitoring: 0,
      'Social Perceptiveness': 0,
      Coordination: 1,
      Persuasion: 1,
      Negotiation: 0,
      Instructing: 0,
      'Service Orientation': 0,
      'Complex Problem Solving': 1,
      'Operations Analysis': 0,
      'Technology Design': 1,
      'Equipment Selection': 1,
      Installation: 1,
      Programming: 1,
      'Operation Monitoring': 0,
      'Operation and Control': 0,
      'Equipment Maintenance': 0,
      Troubleshooting: 1,
      Repairing: 1,
      'Quality Control Analysis': 0,
      'Judgment and Decision Making': 0,
      'Systems Analysis': 0,
      'Systems Evaluation': 0,
      'Time Management': 0,
      'Management of Financial Resources': 1,
      'Management of Material Resources': 0,
      'Management of Personnel Resources': 1,
      'Administration and Management': 0,
      Clerical: 0,
      'Economics and Accounting': 0,
      'Sales and Marketing': 0,
      'Customer and Personal Service': 1,
      'Personnel and Human Resources': 1,
      'Production and Processing': 0,
      'Food Production': 0,
      'Computers and Electronics': 0,
      'Engineering and Technology': 0,
      Design: 0,
      'Building and Construction': 1,
      Mechanical: 1,
      Physics: 0,
      Chemistry: 0,
      Biology: 1,
      Psychology: 1,
      'Sociology and Anthropology': 1,
      Geography: 1,
      'Medicine and Dentistry': 1,
      'Therapy and Counseling': 0,
      'Education and Training': 1,
      'English Language': 1,
      'Foreign Language': 0,
      'Fine Arts': 0,
      'History and Archeology': 0,
      'Philosophy and Theology': 0,
      'Public Safety and Security': 1,
      'Law and Government': 0,
      Telecommunications: 0,
      'Communications and Media': 0,
      Transportation: 0,
      'Document management software': 1,
      'Content workflow software': 0,
      'Customer relationship management CRM software': 1,
      'Enterprise resource planning ERP software': 1,
      'Enterprise application integration software': 0,
      'Accounting software': 0,
      'Data base user interface and query software': 0,
      'Spreadsheet software': 0,
      'Electronic mail software': 1,
      'Presentation software': 0,
      'Project management software': 0,
      'Desktop publishing software': 0,
      'Word processing software': 1,
      'Web platform development software': 0,
      'Data base management system software': 0,
      'Graphics or photo imaging software': 0,
      'Video creation and editing software': 1,
      'Computer aided design CAD software': 1,
      'Access software': 1,
      'Computer aided manufacturing CAM software': 1,
      'Transaction server software': 1,
      'Web page creation and editing software': 0,
      'Sales and marketing software': 1,
      'Data mining software': 0,
      'Human resources software': 1,
      'Business intelligence and data analysis software': 1,
      'Communications server software': 1,
      'Enterprise system management software': 0,
      'Analytical or scientific software': 0,
      'Operating system software': 0,
      'Information retrieval or search software': 0,
      'Transaction security and virus protection software': 1,
      'Development environment software': 0,
      'Network monitoring software': 1,
      'Financial analysis software': 0,
      'Object oriented data base management software': 1,
      'Configuration management software': 1,
      'Object or component oriented development software': 1,
      'Data base reporting software': 0,
      'Backup or archival software': 1,
      'Portal server software': 1,
      'Metadata management software': 1,
      'Application server software': 1,
      'Requirements analysis and system architecture software': 1,
      'Network security and virtual private network VPN equipment software': 1,
      'Medical software': 0,
      'Program testing software': 0,
      'Map creation software': 1,
      'File versioning software': 0,
      'Network security or virtual private network VPN management software': 0,
      'Tax preparation software': 1,
      'Computer based training software': 0,
      'Digital pen': 1,
    },
    {
      JOB_ID: 8,
      ONET_SOC: '17-2072.00',
      date_posted: '2017-02-22',
      job_title: 'Electronic',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 22,
      age_high: 42,
      exp_low: 0,
      exp_high: 99,
      no_position: 1,
      ONET_Title: 'Electronics Engineers, Except Computer',
      Region: 'Central',
      Facullty: 'Engineering',
      'Reading Comprehension': 1,
      'Active Listening': 1,
      Writing: 0,
      Speaking: 0,
      Mathematics: 0,
      Science: 0,
      'Critical Thinking': 1,
      'Active Learning': 1,
      'Learning Strategies': 0,
      Monitoring: 0,
      'Social Perceptiveness': 1,
      Coordination: 1,
      Persuasion: 0,
      Negotiation: 1,
      Instructing: 0,
      'Service Orientation': 0,
      'Complex Problem Solving': 1,
      'Operations Analysis': 0,
      'Technology Design': 0,
      'Equipment Selection': 1,
      Installation: 1,
      Programming: 0,
      'Operation Monitoring': 1,
      'Operation and Control': 1,
      'Equipment Maintenance': 1,
      Troubleshooting: 0,
      Repairing: 0,
      'Quality Control Analysis': 1,
      'Judgment and Decision Making': 0,
      'Systems Analysis': 1,
      'Systems Evaluation': 0,
      'Time Management': 0,
      'Management of Financial Resources': 0,
      'Management of Material Resources': 1,
      'Management of Personnel Resources': 1,
      'Administration and Management': 1,
      Clerical: 0,
      'Economics and Accounting': 0,
      'Sales and Marketing': 1,
      'Customer and Personal Service': 1,
      'Personnel and Human Resources': 1,
      'Production and Processing': 0,
      'Food Production': 1,
      'Computers and Electronics': 1,
      'Engineering and Technology': 1,
      Design: 1,
      'Building and Construction': 1,
      Mechanical: 0,
      Physics: 0,
      Chemistry: 0,
      Biology: 1,
      Psychology: 1,
      'Sociology and Anthropology': 0,
      Geography: 0,
      'Medicine and Dentistry': 1,
      'Therapy and Counseling': 1,
      'Education and Training': 0,
      'English Language': 0,
      'Foreign Language': 0,
      'Fine Arts': 0,
      'History and Archeology': 0,
      'Philosophy and Theology': 0,
      'Public Safety and Security': 0,
      'Law and Government': 0,
      Telecommunications: 1,
      'Communications and Media': 0,
      Transportation: 1,
      'Document management software': 0,
      'Content workflow software': 0,
      'Customer relationship management CRM software': 0,
      'Enterprise resource planning ERP software': 0,
      'Enterprise application integration software': 0,
      'Accounting software': 1,
      'Data base user interface and query software': 0,
      'Spreadsheet software': 1,
      'Electronic mail software': 0,
      'Presentation software': 1,
      'Project management software': 0,
      'Desktop publishing software': 0,
      'Word processing software': 0,
      'Web platform development software': 1,
      'Data base management system software': 1,
      'Graphics or photo imaging software': 0,
      'Video creation and editing software': 0,
      'Computer aided design CAD software': 1,
      'Access software': 0,
      'Computer aided manufacturing CAM software': 1,
      'Transaction server software': 1,
      'Web page creation and editing software': 1,
      'Sales and marketing software': 0,
      'Data mining software': 0,
      'Human resources software': 0,
      'Business intelligence and data analysis software': 1,
      'Communications server software': 1,
      'Enterprise system management software': 0,
      'Analytical or scientific software': 0,
      'Operating system software': 1,
      'Information retrieval or search software': 1,
      'Transaction security and virus protection software': 0,
      'Development environment software': 1,
      'Network monitoring software': 1,
      'Financial analysis software': 1,
      'Object oriented data base management software': 1,
      'Configuration management software': 1,
      'Object or component oriented development software': 0,
      'Data base reporting software': 1,
      'Backup or archival software': 1,
      'Portal server software': 1,
      'Metadata management software': 1,
      'Application server software': 1,
      'Requirements analysis and system architecture software': 0,
      'Network security and virtual private network VPN equipment software': 0,
      'Medical software': 1,
      'Program testing software': 1,
      'Map creation software': 1,
      'File versioning software': 0,
      'Network security or virtual private network VPN management software': 1,
      'Tax preparation software': 1,
      'Computer based training software': 0,
      'Digital pen': 0,
    },
    {
      JOB_ID: 9,
      ONET_SOC: '17-2072.00',
      date_posted: '2017-03-05',
      job_title: 'Electronic',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 22,
      age_high: 31,
      exp_low: 2,
      exp_high: 99,
      no_position: 2,
      ONET_Title: 'Electronics Engineers, Except Computer',
      Region: 'Central',
      Facullty: 'Engineering',
      'Reading Comprehension': 0,
      'Active Listening': 2,
      Writing: 2,
      Speaking: 0,
      Mathematics: 2,
      Science: 2,
      'Critical Thinking': 0,
      'Active Learning': 2,
      'Learning Strategies': 2,
      Monitoring: 0,
      'Social Perceptiveness': 0,
      Coordination: 0,
      Persuasion: 2,
      Negotiation: 2,
      Instructing: 2,
      'Service Orientation': 0,
      'Complex Problem Solving': 0,
      'Operations Analysis': 2,
      'Technology Design': 2,
      'Equipment Selection': 2,
      Installation: 0,
      Programming: 0,
      'Operation Monitoring': 2,
      'Operation and Control': 2,
      'Equipment Maintenance': 2,
      Troubleshooting: 2,
      Repairing: 0,
      'Quality Control Analysis': 0,
      'Judgment and Decision Making': 0,
      'Systems Analysis': 2,
      'Systems Evaluation': 2,
      'Time Management': 0,
      'Management of Financial Resources': 0,
      'Management of Material Resources': 2,
      'Management of Personnel Resources': 0,
      'Administration and Management': 2,
      Clerical: 2,
      'Economics and Accounting': 2,
      'Sales and Marketing': 0,
      'Customer and Personal Service': 2,
      'Personnel and Human Resources': 0,
      'Production and Processing': 2,
      'Food Production': 2,
      'Computers and Electronics': 2,
      'Engineering and Technology': 0,
      Design: 0,
      'Building and Construction': 2,
      Mechanical: 0,
      Physics: 2,
      Chemistry: 2,
      Biology: 2,
      Psychology: 2,
      'Sociology and Anthropology': 0,
      Geography: 0,
      'Medicine and Dentistry': 0,
      'Therapy and Counseling': 2,
      'Education and Training': 0,
      'English Language': 0,
      'Foreign Language': 0,
      'Fine Arts': 2,
      'History and Archeology': 2,
      'Philosophy and Theology': 2,
      'Public Safety and Security': 2,
      'Law and Government': 0,
      Telecommunications: 0,
      'Communications and Media': 2,
      Transportation: 0,
      'Document management software': 2,
      'Content workflow software': 0,
      'Customer relationship management CRM software': 0,
      'Enterprise resource planning ERP software': 2,
      'Enterprise application integration software': 0,
      'Accounting software': 0,
      'Data base user interface and query software': 0,
      'Spreadsheet software': 2,
      'Electronic mail software': 0,
      'Presentation software': 0,
      'Project management software': 0,
      'Desktop publishing software': 0,
      'Word processing software': 0,
      'Web platform development software': 0,
      'Data base management system software': 0,
      'Graphics or photo imaging software': 0,
      'Video creation and editing software': 2,
      'Computer aided design CAD software': 2,
      'Access software': 2,
      'Computer aided manufacturing CAM software': 2,
      'Transaction server software': 0,
      'Web page creation and editing software': 0,
      'Sales and marketing software': 0,
      'Data mining software': 0,
      'Human resources software': 0,
      'Business intelligence and data analysis software': 0,
      'Communications server software': 0,
      'Enterprise system management software': 2,
      'Analytical or scientific software': 0,
      'Operating system software': 0,
      'Information retrieval or search software': 2,
      'Transaction security and virus protection software': 0,
      'Development environment software': 2,
      'Network monitoring software': 2,
      'Financial analysis software': 0,
      'Object oriented data base management software': 2,
      'Configuration management software': 0,
      'Object or component oriented development software': 2,
      'Data base reporting software': 0,
      'Backup or archival software': 2,
      'Portal server software': 0,
      'Metadata management software': 0,
      'Application server software': 0,
      'Requirements analysis and system architecture software': 0,
      'Network security and virtual private network VPN equipment software': 0,
      'Medical software': 0,
      'Program testing software': 2,
      'Map creation software': 2,
      'File versioning software': 2,
      'Network security or virtual private network VPN management software': 0,
      'Tax preparation software': 0,
      'Computer based training software': 0,
      'Digital pen': 2,
    },
    {
      JOB_ID: 10,
      ONET_SOC: '17-2072.00',
      date_posted: '2017-03-05',
      job_title: 'Electronic',
      company: 'TONY Corp',
      industry: 'Energy',
      province: 'NA',
      age_low: 22,
      age_high: 38,
      exp_low: 0,
      exp_high: 99,
      no_position: 2,
      ONET_Title: 'Electronics Engineers, Except Computer',
      Region: 'Central',
      Facullty: 'Engineering',
      'Reading Comprehension': 2,
      'Active Listening': 0,
      Writing: 0,
      Speaking: 0,
      Mathematics: 2,
      Science: 2,
      'Critical Thinking': 0,
      'Active Learning': 0,
      'Learning Strategies': 0,
      Monitoring: 0,
      'Social Perceptiveness': 2,
      Coordination: 2,
      Persuasion: 0,
      Negotiation: 0,
      Instructing: 2,
      'Service Orientation': 0,
      'Complex Problem Solving': 0,
      'Operations Analysis': 2,
      'Technology Design': 2,
      'Equipment Selection': 0,
      Installation: 2,
      Programming: 0,
      'Operation Monitoring': 0,
      'Operation and Control': 2,
      'Equipment Maintenance': 2,
      Troubleshooting: 2,
      Repairing: 0,
      'Quality Control Analysis': 0,
      'Judgment and Decision Making': 2,
      'Systems Analysis': 0,
      'Systems Evaluation': 0,
      'Time Management': 0,
      'Management of Financial Resources': 0,
      'Management of Material Resources': 2,
      'Management of Personnel Resources': 0,
      'Administration and Management': 0,
      Clerical: 0,
      'Economics and Accounting': 0,
      'Sales and Marketing': 2,
      'Customer and Personal Service': 0,
      'Personnel and Human Resources': 2,
      'Production and Processing': 0,
      'Food Production': 2,
      'Computers and Electronics': 0,
      'Engineering and Technology': 2,
      Design: 2,
      'Building and Construction': 0,
      Mechanical: 0,
      Physics: 2,
      Chemistry: 0,
      Biology: 2,
      Psychology: 2,
      'Sociology and Anthropology': 0,
      Geography: 0,
      'Medicine and Dentistry': 0,
      'Therapy and Counseling': 0,
      'Education and Training': 0,
      'English Language': 2,
      'Foreign Language': 0,
      'Fine Arts': 2,
      'History and Archeology': 2,
      'Philosophy and Theology': 2,
      'Public Safety and Security': 2,
      'Law and Government': 2,
      Telecommunications: 0,
      'Communications and Media': 2,
      Transportation: 0,
      'Document management software': 0,
      'Content workflow software': 2,
      'Customer relationship management CRM software': 0,
      'Enterprise resource planning ERP software': 0,
      'Enterprise application integration software': 0,
      'Accounting software': 0,
      'Data base user interface and query software': 2,
      'Spreadsheet software': 0,
      'Electronic mail software': 0,
      'Presentation software': 0,
      'Project management software': 2,
      'Desktop publishing software': 2,
      'Word processing software': 2,
      'Web platform development software': 2,
      'Data base management system software': 2,
      'Graphics or photo imaging software': 0,
      'Video creation and editing software': 2,
      'Computer aided design CAD software': 0,
      'Access software': 2,
      'Computer aided manufacturing CAM software': 2,
      'Transaction server software': 2,
      'Web page creation and editing software': 2,
      'Sales and marketing software': 2,
      'Data mining software': 0,
      'Human resources software': 0,
      'Business intelligence and data analysis software': 0,
      'Communications server software': 0,
      'Enterprise system management software': 2,
      'Analytical or scientific software': 2,
      'Operating system software': 0,
      'Information retrieval or search software': 2,
      'Transaction security and virus protection software': 0,
      'Development environment software': 0,
      'Network monitoring software': 0,
      'Financial analysis software': 0,
      'Object oriented data base management software': 2,
      'Configuration management software': 2,
      'Object or component oriented development software': 2,
      'Data base reporting software': 0,
      'Backup or archival software': 0,
      'Portal server software': 0,
      'Metadata management software': 2,
      'Application server software': 0,
      'Requirements analysis and system architecture software': 2,
      'Network security and virtual private network VPN equipment software': 0,
      'Medical software': 2,
      'Program testing software': 0,
      'Map creation software': 2,
      'File versioning software': 0,
      'Network security or virtual private network VPN management software': 0,
      'Tax preparation software': 0,
      'Computer based training software': 0,
      'Digital pen': 0,
    },
  ],
  skill: [
    {
      name: 'Reading Comprehension',
      value: 4,
    },
    {
      name: 'Active Listening',
      value: 7,
    },
    {
      name: 'Writing',
      value: 10,
    },
    {
      name: 'Speaking',
      value: 5,
    },
    {
      name: 'Mathematics',
      value: 10,
    },
    {
      name: 'Science',
      value: 12,
    },
    {
      name: 'Critical Thinking',
      value: 9,
    },
    {
      name: 'Active Learning',
      value: 8,
    },
    {
      name: 'Learning Strategies',
      value: 7,
    },
    {
      name: 'Monitoring',
      value: 3,
    },
    {
      name: 'Social Perceptiveness',
      value: 5,
    },
    {
      name: 'Coordination',
      value: 8,
    },
    {
      name: 'Persuasion',
      value: 7,
    },
    {
      name: 'Negotiation',
      value: 8,
    },
    {
      name: 'Instructing',
      value: 5,
    },
    {
      name: 'Service Orientation',
      value: 7,
    },
    {
      name: 'Complex Problem Solving',
      value: 7,
    },
    {
      name: 'Operations Analysis',
      value: 6,
    },
    {
      name: 'Technology Design',
      value: 9,
    },
    {
      name: 'Equipment Selection',
      value: 8,
    },
    {
      name: 'Installation',
      value: 5,
    },
    {
      name: 'Programming',
      value: 7,
    },
    {
      name: 'Operation Monitoring',
      value: 8,
    },
    {
      name: 'Operation and Control',
      value: 11,
    },
    {
      name: 'Equipment Maintenance',
      value: 10,
    },
    {
      name: 'Troubleshooting',
      value: 9,
    },
    {
      name: 'Repairing',
      value: 2,
    },
    {
      name: 'Quality Control Analysis',
      value: 3,
    },
    {
      name: 'Judgment and Decision Making',
      value: 4,
    },
    {
      name: 'Systems Analysis',
      value: 9,
    },
    {
      name: 'Systems Evaluation',
      value: 8,
    },
    {
      name: 'Time Management',
      value: 8,
    },
    {
      name: 'Management of Financial Resources',
      value: 3,
    },
    {
      name: 'Management of Material Resources',
      value: 11,
    },
    {
      name: 'Management of Personnel Resources',
      value: 4,
    },
  ],
  tool: [
    {
      name: 'Document management software',
      value: 9,
    },
    {
      name: 'Content workflow software',
      value: 9,
    },
    {
      name: 'Customer relationship management CRM software',
      value: 3,
    },
    {
      name: 'Enterprise resource planning ERP software',
      value: 8,
    },
    {
      name: 'Enterprise application integration software',
      value: 3,
    },
    {
      name: 'Accounting software',
      value: 5,
    },
    {
      name: 'Data base user interface and query software',
      value: 7,
    },
    {
      name: 'Spreadsheet software',
      value: 5,
    },
    {
      name: 'Electronic mail software',
      value: 6,
    },
    {
      name: 'Presentation software',
      value: 2,
    },
    {
      name: 'Project management software',
      value: 4,
    },
    {
      name: 'Desktop publishing software',
      value: 5,
    },
    {
      name: 'Word processing software',
      value: 8,
    },
    {
      name: 'Web platform development software',
      value: 9,
    },
    {
      name: 'Data base management system software',
      value: 6,
    },
    {
      name: 'Graphics or photo imaging software',
      value: 5,
    },
    {
      name: 'Video creation and editing software',
      value: 9,
    },
    {
      name: 'Computer aided design CAD software',
      value: 9,
    },
    {
      name: 'Access software',
      value: 8,
    },
    {
      name: 'Computer aided manufacturing CAM software',
      value: 9,
    },
    {
      name: 'Transaction server software',
      value: 7,
    },
    {
      name: 'Web page creation and editing software',
      value: 5,
    },
    {
      name: 'Sales and marketing software',
      value: 7,
    },
    {
      name: 'Data mining software',
      value: 3,
    },
    {
      name: 'Human resources software',
      value: 8,
    },
    {
      name: 'Business intelligence and data analysis software',
      value: 7,
    },
    {
      name: 'Communications server software',
      value: 8,
    },
    {
      name: 'Enterprise system management software',
      value: 6,
    },
    {
      name: 'Analytical or scientific software',
      value: 9,
    },
    {
      name: 'Operating system software',
      value: 5,
    },
    {
      name: 'Information retrieval or search software',
      value: 10,
    },
    {
      name: 'Transaction security and virus protection software',
      value: 4,
    },
    {
      name: 'Development environment software',
      value: 8,
    },
    {
      name: 'Network monitoring software',
      value: 9,
    },
    {
      name: 'Financial analysis software',
      value: 4,
    },
    {
      name: 'Object oriented data base management software',
      value: 12,
    },
    {
      name: 'Configuration management software',
      value: 7,
    },
    {
      name: 'Object or component oriented development software',
      value: 8,
    },
    {
      name: 'Data base reporting software',
      value: 6,
    },
    {
      name: 'Backup or archival software',
      value: 8,
    },
    {
      name: 'Portal server software',
      value: 6,
    },
    {
      name: 'Metadata management software',
      value: 7,
    },
    {
      name: 'Application server software',
      value: 5,
    },
    {
      name: 'Requirements analysis and system architecture software',
      value: 7,
    },
    {
      name: 'Network security and virtual private network VPN equipment software',
      value: 9,
    },
    {
      name: 'Medical software',
      value: 6,
    },
    {
      name: 'Program testing software',
      value: 4,
    },
    {
      name: 'Map creation software',
      value: 13,
    },
    {
      name: 'File versioning software',
      value: 8,
    },
    {
      name: 'Network security or virtual private network VPN management software',
      value: 5,
    },
    {
      name: 'Tax preparation software',
      value: 6,
    },
    {
      name: 'Computer based training software',
      value: 3,
    },
    {
      name: 'Digital pen',
      value: 12,
    },
  ],
  knowledge: [
    {
      name: 'Administration and Management',
      value: 5,
    },
    {
      name: 'Clerical',
      value: 8,
    },
  ],
};
